In [19]:
import os
os.chdir(r"C:\Users\mattc\OneDrive\Documents\eso8GKofnumUkahs")
os.getcwd()

'C:\\Users\\mattc\\OneDrive\\Documents\\eso8GKofnumUkahs'

In [20]:
import numpy as np
import pandas as pd
from lazypredict.Supervised import LazyClassifier
from sklearn.metrics import f1_score

from src.data.prepare_data import x_y_split, tt_split

In [21]:
data = pd.read_csv('data/raw/ACME-HappinessSurvey2020.csv')

x, y = x_y_split(data)

x_train, x_test, y_train, y_test = tt_split(x, y)

In [29]:
def custom_f1(y_true, y_pred):
    return f1_score(y_true, y_pred, average='weighted')

lzclf = LazyClassifier(verbose=0, ignore_warnings=True, custom_metric=custom_f1)
models, predictions = lzclf.fit(x_train, x_test, y_train, y_test)

In [32]:
models

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Precision,Recall,custom_f1,Time Taken
Model,,,,,,,,
PassiveAggressiveClassifier,0.615385,0.601190,0.654762,0.600962,0.617521,0.615385,0.600962,0.034257
XGBClassifier,0.615385,0.595238,0.505952,0.585219,0.630769,0.615385,0.585219,0.146022
QuadraticDiscriminantAnalysis,0.576923,0.571429,0.613095,0.575020,0.574825,0.576923,0.575020,0.030737
KNeighborsClassifier,0.576923,0.565476,0.529762,0.567175,0.573152,0.576923,0.567175,0.045693
ExtraTreeClassifier,0.576923,0.559524,0.562500,0.553306,0.575477,0.576923,0.553306,0.030595
ExtraTreesClassifier,0.576923,0.559524,0.577381,0.553306,0.575477,0.576923,0.553306,0.218588
RidgeClassifier,0.538462,0.529762,0.529762,0.532867,0.533654,0.538462,0.532867,0.032570
LogisticRegression,0.538462,0.529762,0.535714,0.532867,0.533654,0.538462,0.532867,0.028844
LinearDiscriminantAnalysis,0.538462,0.529762,0.529762,0.532867,0.533654,0.538462,0.532867,0.034037
LinearSVC,0.538462,0.529762,0.523810,0.532867,0.533654,0.538462,0.532867,0.033977
BernoulliNB,0.538462,0.529762,0.607143,0.532867,0.533654,0.538462,0.532867,0.037000
GaussianNB,0.538462,0.523810,0.619048,0.521154,0.529915,0.538462,0.521154,0.028442
CalibratedClassifierCV,0.538462,0.523810,0.511905,0.521154,0.529915,0.538462,0.521154,0.078766
RidgeClassifierCV,0.538462,0.523810,0.523810,0.521154,0.529915,0.538462,0.521154,0.034700
SGDClassifier,0.538462,0.523810,0.690476,0.521154,0.529915,0.538462,0.521154,0.029905
RandomForestClassifier,0.538462,0.517857,0.508929,0.502262,0.526923,0.538462,0.502262,0.281637
DummyClassifier,0.538462,0.500000,0.500000,0.376923,0.289941,0.538462,0.376923,0.027649
BaggingClassifier,0.500000,0.494048,0.526786,0.497751,0.496970,0.500000,0.497751,0.081352
NearestCentroid,0.500000,0.494048,0.625000,0.497751,0.496970,0.500000,0.497751,0.035261
LabelSpreading,0.500000,0.488095,0.613095,0.488479,0.490196,0.500000,0.488479,0.035663
NuSVC,0.500000,0.488095,0.500000,0.488479,0.490196,0.500000,0.488479,0.033707
LabelPropagation,0.500000,0.482143,0.595238,0.472089,0.481203,0.500000,0.472089,0.038487
AdaBoostClassifier,0.500000,0.476190,0.494048,0.447059,0.466667,0.500000,0.447059,0.225788
DecisionTreeClassifier,0.461538,0.452381,0.470238,0.455012,0.453846,0.461538,0.455012,0.032820
SVC,0.461538,0.446429,0.476190,0.441346,0.442308,0.461538,0.441346,0.032502
Perceptron,0.423077,0.404762,0.464286,0.390872,0.386929,0.423077,0.390872,0.031628

In [39]:
from sklearn.model_selection import train_test_split

data = pd.read_csv('data/raw/ACME-HappinessSurvey2020.csv')

x = data.drop(columns=['Y'])
y = data['Y']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

lzclf = LazyClassifier(verbose=0, ignore_warnings=True, custom_metric=custom_f1)
models, predictions = lzclf.fit(x_train, x_test, y_train, y_test)

models.loc[['XGBClassifier', 'RandomForestClassifier', 'KNeighborsClassifier']]

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Precision,Recall,custom_f1,Time Taken
Model,,,,,,,,
XGBClassifier,0.538462,0.5125,0.512500,0.538462,0.538462,0.538462,0.538462,0.343222
RandomForestClassifier,0.538462,0.5125,0.531250,0.538462,0.538462,0.538462,0.538462,0.329828
KNeighborsClassifier,0.538462,0.4750,0.559375,0.506410,0.497436,0.538462,0.506410,0.035245

In [40]:
from sklearn.model_selection import train_test_split

data = pd.read_csv('data/raw/ACME-HappinessSurvey2020.csv')

x = data.drop(columns=['Y'])
y = data['Y']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2)

lzclf = LazyClassifier(verbose=0, ignore_warnings=True, custom_metric=custom_f1)
models, predictions = lzclf.fit(x_train, x_test, y_train, y_test)

models.loc[['XGBClassifier', 'RandomForestClassifier', 'KNeighborsClassifier']]

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Precision,Recall,custom_f1,Time Taken
Model,,,,,,,,
XGBClassifier,0.576923,0.58125,0.575000,0.582632,0.603550,0.576923,0.582632,0.132717
RandomForestClassifier,0.615385,0.63125,0.593750,0.619963,0.653846,0.615385,0.619963,0.272339
KNeighborsClassifier,0.500000,0.48125,0.453125,0.503840,0.509091,0.500000,0.503840,0.034459

In [41]:
from sklearn.model_selection import train_test_split

data = pd.read_csv('data/raw/ACME-HappinessSurvey2020.csv')

x = data.drop(columns=['Y'])
y = data['Y']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=3)

lzclf = LazyClassifier(verbose=0, ignore_warnings=True, custom_metric=custom_f1)
models, predictions = lzclf.fit(x_train, x_test, y_train, y_test)

models.loc[['XGBClassifier', 'RandomForestClassifier', 'KNeighborsClassifier']]

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Precision,Recall,custom_f1,Time Taken
Model,,,,,,,,
XGBClassifier,0.730769,0.730769,0.721893,0.727136,0.743750,0.730769,0.727136,0.097513
RandomForestClassifier,0.538462,0.538462,0.609467,0.535714,0.539394,0.538462,0.535714,0.260919
KNeighborsClassifier,0.538462,0.538462,0.662722,0.512500,0.548872,0.538462,0.512500,0.034131